export const SET_COMMENT = 'setComment'
export const SET_ALL_COMMENTS = 'setAllComments'
export const CHANGE_COMMENT_TO_ANOTHER_COMMENTTYPE = 'changeCommentToAnotherCommentType'
export const SET_ACTION = 'setAction'
export const SET_ACTIONS = 'setActions'
export const REMOVE_ACTION = 'removeAction'